// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type College struct {
	CollegeID int32  `json:"college_id"`
	Name      string `json:"name"`
}

type Funnel struct {
	FunnelID int32  `json:"funnel_id"`
	Name     string `json:"name"`
}

type Invoice struct {
	InvoiceID      int64          `json:"invoice_id"`
	StudentID      int64          `json:"student_id"`
	LessonID       int64          `json:"lesson_id"`
	LessonDuration time.Time      `json:"lesson_duration"`
	HourlyAmount   string         `json:"hourly_amount"`
	TotalAmount    string         `json:"total_amount"`
	Notes          sql.NullString `json:"notes"`
}

type Lesson struct {
	LessonID   int64          `json:"lesson_id"`
	HeldOn     time.Time      `json:"held_on"`
	LocationID int32          `json:"location_id"`
	Duration   time.Time      `json:"duration"`
	SubjectID  int32          `json:"subject_id"`
	Notes      sql.NullString `json:"notes"`
}

type LessonLocation struct {
	LocationID int32  `json:"location_id"`
	Name       string `json:"name"`
}

type LessonSubject struct {
	SubjectID int32  `json:"subject_id"`
	Name      string `json:"name"`
}

type Payment struct {
	PaymentID        int64     `json:"payment_id"`
	ReceiptID        int64     `json:"receipt_id"`
	PayedAt          time.Time `json:"payed_at"`
	Amount           string    `json:"amount"`
	PaymentMethodsID int32     `json:"payment_methods_id"`
}

type PaymentMethod struct {
	PaymentMethodID int32  `json:"payment_method_id"`
	Name            string `json:"name"`
}

type Receipt struct {
	ReceiptID   int64          `json:"receipt_id"`
	StudentID   int64          `json:"student_id"`
	ReceivedAt  time.Time      `json:"received_at"`
	TotalAmount string         `json:"total_amount"`
	Notes       sql.NullString `json:"notes"`
}

type Student struct {
	StudentID    int64          `json:"student_id"`
	FirstName    string         `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	EmailAddress sql.NullString `json:"email_address"`
	CollegeID    sql.NullInt32  `json:"college_id"`
	FunnelID     sql.NullInt32  `json:"funnel_id"`
	Notes        sql.NullString `json:"notes"`
	CreatedAt    time.Time      `json:"created_at"`
}
