// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateCollege(ctx context.Context, name string) (*College, error)
	CreateFunnel(ctx context.Context, name string) (*Funnel, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (*Invoice, error)
	CreateLesson(ctx context.Context, arg CreateLessonParams) (*Lesson, error)
	CreateLessonLocation(ctx context.Context, name string) (*LessonLocation, error)
	CreateLessonSubject(ctx context.Context, name string) (*LessonSubject, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (*Payment, error)
	CreatePaymentMethod(ctx context.Context, name string) (*PaymentMethod, error)
	CreateReceipt(ctx context.Context, arg CreateReceiptParams) (*Receipt, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (*Student, error)
	DeleteCollege(ctx context.Context, collegeID int64) error
	DeleteFunnel(ctx context.Context, funnelID int64) error
	DeleteInvoice(ctx context.Context, invoiceID int64) error
	DeleteInvoicesByLesson(ctx context.Context, lessonID int64) error
	DeleteLesson(ctx context.Context, lessonID int64) error
	DeleteLessonLocation(ctx context.Context, locationID int64) error
	DeleteLessonSubject(ctx context.Context, subjectID int64) error
	DeletePayment(ctx context.Context, paymentID int64) error
	DeletePaymentMethod(ctx context.Context, paymentMethodID int64) error
	DeletePaymentsByReceipt(ctx context.Context, receiptID int64) error
	DeleteReceipt(ctx context.Context, receiptID int64) error
	DeleteStudent(ctx context.Context, studentID int64) error
	GetCollege(ctx context.Context, collegeID int64) (*College, error)
	GetFunnel(ctx context.Context, funnelID int64) (*Funnel, error)
	GetInvoice(ctx context.Context, invoiceID int64) (*Invoice, error)
	GetInvoicesByLesson(ctx context.Context, lessonID int64) ([]*Invoice, error)
	GetInvoicesByStudent(ctx context.Context, studentID int64) ([]*Invoice, error)
	GetLesson(ctx context.Context, lessonID int64) (*Lesson, error)
	GetLessonLocation(ctx context.Context, locationID int64) (*LessonLocation, error)
	GetLessonSubject(ctx context.Context, subjectID int64) (*LessonSubject, error)
	GetPayment(ctx context.Context, paymentID int64) (*Payment, error)
	GetPaymentMethod(ctx context.Context, paymentMethodID int64) (*PaymentMethod, error)
	GetPayments(ctx context.Context, receiptID int64) ([]*Payment, error)
	GetReceipt(ctx context.Context, receiptID int64) (*Receipt, error)
	GetReceiptsByStudent(ctx context.Context, arg GetReceiptsByStudentParams) ([]*Receipt, error)
	GetStudent(ctx context.Context, studentID int64) (*Student, error)
	ListColleges(ctx context.Context, arg ListCollegesParams) ([]*College, error)
	ListFunnels(ctx context.Context, arg ListFunnelsParams) ([]*Funnel, error)
	ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]*Invoice, error)
	ListLessonLocations(ctx context.Context, arg ListLessonLocationsParams) ([]*LessonLocation, error)
	ListLessonSubjects(ctx context.Context, arg ListLessonSubjectsParams) ([]*LessonSubject, error)
	ListLessons(ctx context.Context, arg ListLessonsParams) ([]*Lesson, error)
	ListPaymentMethods(ctx context.Context, arg ListPaymentMethodsParams) ([]*PaymentMethod, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]*Payment, error)
	ListReceipts(ctx context.Context, arg ListReceiptsParams) ([]*Receipt, error)
	ListStudents(ctx context.Context, arg ListStudentsParams) ([]*Student, error)
	UpdateCollege(ctx context.Context, arg UpdateCollegeParams) error
	UpdateFunnel(ctx context.Context, arg UpdateFunnelParams) error
	UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) error
	UpdateLesson(ctx context.Context, arg UpdateLessonParams) error
	UpdateLessonLocation(ctx context.Context, arg UpdateLessonLocationParams) error
	UpdateLessonSubject(ctx context.Context, arg UpdateLessonSubjectParams) error
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error
	UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) error
	UpdateReceipt(ctx context.Context, arg UpdateReceiptParams) error
	UpdateReceiptAmount(ctx context.Context, arg UpdateReceiptAmountParams) error
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) error
}

var _ Querier = (*Queries)(nil)
